[package]
name = "icy_view"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.22"
egui_extras = { version="0.22.0", features = ["svg"] }
egui_glow = "0.22.0"
glow = "0.12.2"

icy_engine = { git = "https://github.com/mkrueger/icy_engine.git" }
